version: '3.9'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postres_pass
      POSTGRES_USER: postgres
      POSTGRES_DB: default-db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web:
     build: .
     ports:
      - "8000:80"
     depends_on:
      - db

volumes:
  db-data:
