version: '3.9'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 789qwER
      POSTGRES_USER: postgres
      POSTGRES_DB: vr_backend
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

  web:
     build: .
     ports:
      - "8000:80"
     depends_on:
      - db

volumes:
  db-data:
